language: scala

sudo: false

scala:
  - "2.12.4"

jdk:
  - oraclejdk8

script:
  - sbt -J-XX:ReservedCodeCacheSize=128m ++$TRAVIS_SCALA_VERSION ";compile"

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot